spanish_tickers = [
        {"ticker": "ANA.MC", "name": "Acciona"},
        {"ticker": "ANE.MC", "name": "Acciona Energía"},
        {"ticker": "ACX.MC", "name": "Acerinox"},
        {"ticker": "ACS.MC", "name": "ACS"},
        {"ticker": "AENA.MC", "name": "Aena"},
        {"ticker": "AMS.MC", "name": "Amadeus"},
        {"ticker": "MTS.MC", "name": "ArcelorMittal"},
        {"ticker": "SAB.MC", "name": "Banco Sabadell"},
        {"ticker": "SAN.MC", "name": "Banco Santander"},
        {"ticker": "BKT.MC", "name": "Bankinter"},
        {"ticker": "BBVA.MC", "name": "BBVA"},
        {"ticker": "CABK.MC", "name": "CaixaBank"},
        {"ticker": "CLNX.MC", "name": "Cellnex"},
        {"ticker": "ENG.MC", "name": "Enagás"},
        {"ticker": "ELE.MC", "name": "Endesa"},
        {"ticker": "FER.MC", "name": "Ferrovial"},
        {"ticker": "FDR.MC", "name": "Fluidra"},
        {"ticker": "GRF.MC", "name": "Grifols"},
        {"ticker": "IAG.MC", "name": "IAG"},
        {"ticker": "IBE.MC", "name": "Iberdrola"},
        {"ticker": "ITX.MC", "name": "Inditex"},
        {"ticker": "IDR.MC", "name": "Indra"},
        {"ticker": "LOG.MC", "name": "Logista"},
        {"ticker": "MAP.MC", "name": "Mapfre"},
        {"ticker": "MRL.MC", "name": "Merlin Properties"},
        {"ticker": "NTGY.MC", "name": "Naturgy"},
        {"ticker": "RED.MC", "name": "Redeia (Red Eléctrica)"},
        {"ticker": "REP.MC", "name": "Repsol"},
        {"ticker": "ROVI.MC", "name": "Rovi"},
        {"ticker": "SCYR.MC", "name": "Sacyr"},
        {"ticker": "SLR.MC", "name": "Solaria"},
        {"ticker": "TEF.MC", "name": "Telefónica"},
        {"ticker": "UNI.MC", "name": "Unicaja"},
        {"ticker": "VIS.MC", "name": "Viscofan"},
        {"ticker": "AMP.MC", "name": "Amper"},
        {"ticker": "ADX.MC", "name": "Audax Renovables"},
        {"ticker": "ATRY.MC", "name": "Atrys Health"},
        {"ticker": "CAF.MC", "name": "CAF"},
        {"ticker": "CIE.MC", "name": "CIE Automotive"},
        {"ticker": "DOM.MC", "name": "Dominion"},
        {"ticker": "EBRO.MC", "name": "Ebro Foods"},
        {"ticker": "ENO.MC", "name": "Elecnor"},
        {"ticker": "ENC.MC", "name": "Ence"},
        {"ticker": "FAE.MC", "name": "Faes Farma"},
        {"ticker": "GEST.MC", "name": "Gestamp"},
        {"ticker": "LGT.MC", "name": "Lingotes Especiales"},
        {"ticker": "HOME.MC", "name": "Neinor Homes"},
        {"ticker": "OHLA.MC", "name": "OHL"},
        {"ticker": "ORY.MC", "name": "Oryzon"},
        {"ticker": "PSG.MC", "name": "Prosegur"},
        {"ticker": "CASH.MC", "name": "Prosegur Cash"},
        {"ticker": "TLGO.MC", "name": "Talgo"},
        {"ticker": "TUB.MC", "name": "Tubacex"},
        {"ticker": "TRG.MC", "name": "Tubos Reunidos"},
    ]
